service:
  name: marks-aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs6.10

functions:
  api:
    handler: handler.api
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

